server:
  port: 8080
  mode: debug # debug or release

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: {{.ProjectName}}_dev
  sslmode: disable

log:
  level: info
  file:
    path: logs/app.log
    max_size: 100    # megabytes
    max_age: 7       # days
    max_backups: 3   # number of backups
    compress: true   # compress rotated files