server:
  port: 8080
  mode: debug # debug or release

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: {{.ProjectName}}
  sslmode: disable

log:
  level: info
  filename: logs/app.log
  maxsize: 100    # megabytes
  maxage: 7       # days
  maxbackups: 3   # number of backups 