name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - name: Build for multiple platforms
        run: |
          mkdir -p bin
          # Build for macOS
          GOOS=darwin GOARCH=amd64 go build -o bin/genst-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o bin/genst-darwin-arm64
          
          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -o bin/genst-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o bin/genst-linux-arm64
          
          # Add execute permission
          chmod +x bin/*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/genst-darwin-amd64
            bin/genst-darwin-arm64
            bin/genst-linux-amd64
            bin/genst-linux-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/
          retention-days: 5